export const Users = [
  {
    id: 1,
    profilePicture: "person/my.png",
    username: "Het Patel",
  },
  {
    id: 2,
    profilePicture: "person/2.jpeg",
    username: "Aayush Patel",
  },
  {
    id: 3,
    profilePicture: "person/3.jpeg",
    username: "Sujal Patel",
  },
  {
    id: 4,
    profilePicture: "person/4.jpeg",
    username: "Krish Patel",
  },
  {
    id: 5,
    profilePicture: "person/5.jpeg",
    username: "Devarsh Patel",
  },
  {
    id: 6,
    profilePicture: "person/6.jpeg",
    username: "Dhruv Shah",
  },
  {
    id: 7,
    profilePicture: "person/7.jpeg",
    username: "Sarthak Tailor",
  },
  {
    id: 8,
    profilePicture: "person/8.jpeg",
    username: "Dharmik Jethva",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "The Incredible Nature.",
    photo: "post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 69,
    comment: 11,
  },
  {
    id: 2,
    photo: "post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "No Description.",
    photo: "post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 71,
    comment: 8,
  },
  {
    id: 5,
    photo: "post/5.jpeg",
    date: "5 hours ago",
    userId: 2,
    like: 43,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 124,
    comment: 12,
  },
  {
    id: 7,
    desc: "Keep Smiling.",
    photo: "post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 94,
    comment: 18,
  },
  {
    id: 8,
    photo: "post/8.jpeg",
    date: "3 days ago",
    userId: 4,
    like: 12,
    comment: 2,
  },
];
